name: etradebot
channels:
  - conda-forge
  - defaults
dependencies:
  - blpapi==3.19.1
  - keyring==23.13.1
  - matplotlib==3.7.1
  - pandas==1.5.3
  - pip==22.2.2
  - statsmodels==0.13.5
  - pip:
    - cvxpy==1.3.0
    - jupyterlab==3.6.1
    - numpy==1.24.2
    - pyportfolioopt==1.5.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - selenium==4.8.2
    - tqdm==4.65.0
    - xmltodict==0.13.0
    - yahooquery==2.3.0
    - yfinance==0.2.12
    - git+https://github.com/nathanramoscfa/pyetrade.git#egg=pyetrade
    - git+https://github.com/PaulMest/tia.git#egg=tia